name: Comment on Merged PR

on:
  pull_request:
    types: [closed]

jobs:
  comment-on-pr:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      github.event.pull_request.user.login != github.repository_owner
    runs-on: ubuntu-latest

    steps:
      - name: Comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequest = context.payload.pull_request;
            const issue_number = pullRequest.number;
            const user_login = pullRequest.user.login;

            // Check if the author is neither 'dependabot[bot]' nor the repository owner
            if (user_login !== 'dependabot[bot]' && user_login !== context.repo.owner) {
              const commentBody = `
                Hi @${user_login}!

                This task has been completed and will be implemented in the next project release.

                Thank you for your contribution!
              `;

              await github.issues.createComment({
                ...context.repo,
                issue_number: issue_number,
                body: commentBody.trim()
              });
            }
